name: SyliusBatteryIncludedPlugin
type: php
php_version: "8.4"
webserver_type: apache-fpm
database:
    type: mariadb
    version: "10.11"
docroot: vendor/sylius/test-application/public
composer_version: "2"
nodejs_version: "20"